---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew

  tasks:
    - include_tasks: tasks/symlinks.yml
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/rust.yml
    - include_tasks: tasks/dock.yml
