---
- name: Install spacemacs.
  git:
    repo: 'https://github.com/syl20bnr/spacemacs.git'
    dest: ~/.emacs.d
    update: yes

- name: Create .bash configuration folder.
  file:
    path: ~/.bash
    state: directory
  become: yes

- name: Install git aware prompt.
  git:
    repo: 'https://github.com/jimeh/git-aware-prompt.git'
    dest: ~/.bash/git-aware-prompt
    update: yes

- name: Install git completions.
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.bash/git-completion.bash
    mode: 0655

- name: Create directory for vim-plug.
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory
  become: yes

- name: Install vim-plug.
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    mode: 0655
