---
- name: Check if rustup is installed.
  shell: command -v rustup
  failed_when: false
  register: check_rustup

- name: Install rustup (if needed).
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y
  when: check_rustup.stdout.find('rustup') != 0

- name: Check if nightly toolchain is installed.
  command: rustup show
  register: check_nightly

- name: Install nightly toolchain (if needed).
  command: rustup install nightly
  when: check_nightly.stdout.find('nightly') != 0

- name: Set nightly as default.
  shell: rustup default nightly

- name: Add rust-src component.
  shell: rustup component add rust-src

- name: Check if cargo-update is installed.
  shell: cargo install --list
  register: check_cargo_update

- name: Install cargo-update.
  shell: cargo install cargo-update
  failed_when: false
  when: check_cargo_update.stdout.find('cargo-update') != 0
